"""episodic memory: bounded accumulation of verbal lessons across attempts + pre-admission validation (Issue #22).

A container that stores the "verbal guidance (lesson)" generated by the outer Reflexion loop
(report.md S4.4 / S5 Phase3) at episode boundaries and wires it into the next episode's
context with ``render()``. This module is a **leaf module** and depends only on
``loop_agent.state`` (StepRecord); it has no LLM dependency. Inject :data:`LessonVerifier`
when semantic validation is needed.

Safety design (report.md S6 + RQGM / Issue #4): invariants guaranteed here:

- **Pre-admission validation (memory pre-admission validation / reject false lesson
  injection)**: before a lesson is admitted, it must pass the **structural
  (LLM-independent) gate** in :func:`default_admit`. The lesson's ``provenance`` must match
  the signature (:func:`step_signature`) of an actual trajectory step, ``support`` must meet
  the threshold, and the text must stay within the limit. Injected fabricated lessons
  (not tied to a real step) are rejected by the ``provenance`` mismatch.
- **Do not trust self-reported support**: ``Lesson.support`` is a value that the **driver
  (run_reflexion) recomputes from authoritative signals and overwrites**, so forged values
  from the ``reflect`` hook do not affect admission (the driver overwrites them; see
  :mod:`loop_agent.reflexion`).
- **Prevent bloat and degradation (iteration limits)**: stored lessons and next-context
  rendering are both bounded by the retained lesson count ``cap``, the per-lesson character
  limit ``per_lesson_chars``, and the total byte limit for ``render()``,
  ``render_byte_cap`` (mitigating the "4x expansion in 3 iterations" noted in report.md).
- **Deterministic, value-aware eviction**: when capacity is exceeded, discard lessons in the
  deterministic order **lowest support -> oldest episode**. This prevents low-support
  peripheral lessons from pushing out high-support load-bearing lessons (= keeps useful
  learning). Eviction order does not depend on scores the agent can manipulate.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field, replace
from typing import Any, Callable, Sequence

from .errors import ConfigError
from .state import StepRecord


def step_signature(record: StepRecord) -> str:
    """Return a **content-based** stable signature for a trajectory step (for provenance grounding).

    If only iteration were used, a signature such as ``step-0`` could be forged because it
    always exists, so this uses a short hash that also includes observation / detail /
    goal_met. Only lessons that cite an actual step can match; injected lessons without
    trajectory access cannot.
    """
    payload = f"{record.iteration}|{record.goal_met}|{record.detail}|{record.observation!r}"
    digest = hashlib.sha256(payload.encode("utf-8", "surrogatepass")).hexdigest()
    return f"step-{record.iteration}-{digest[:12]}"


def trajectory_signatures(history: Sequence[StepRecord]) -> frozenset[str]:
    """Signature set for every trajectory step (used for provenance matching)."""
    return frozenset(step_signature(s) for s in history)


@dataclass(frozen=True)
class Lesson:
    """One verbal guidance item (the accumulation unit for Reflexion verbal reinforcement).

    - ``text``       : Verbal guidance wired into the next context.
    - ``episode``    : Source episode number (used for eviction tie-breaks and auditing).
    - ``provenance`` : Source step signature (:func:`step_signature`), the grounding key.
    - ``support``    : Support score **recomputed by the driver** from authoritative signals.
      Values set by ``reflect`` are overwritten by the driver, so this is the only value that
      admission may trust.
    """

    text: str
    episode: int
    provenance: str
    support: float = 0.0


@dataclass(frozen=True)
class LessonVerdict:
    """Pre-admission validation verdict. If ``admit`` is False, the lesson is not stored."""

    admit: bool
    reason: str = ""


# Pre-admission validation hook: (lesson, outcome) -> LessonVerdict. outcome is a read-only
# view with ``.history`` (duck typing; this keeps leaf-module status by not importing
# EpisodeOutcome). The default is :func:`default_admit` (structural). Callers can replace it
# for semantic or effect-based validation.
LessonVerifier = Callable[[Lesson, Any], LessonVerdict]


# Default threshold for the structural gate. support is a value the driver recomputes from
# grounding (equivalent to 0.0 or 1.0), so requiring > 0 rejects "injected lessons not tied
# to an actual step."
DEFAULT_MIN_SUPPORT = 1e-9


def default_admit(lesson: Lesson, outcome: Any) -> LessonVerdict:
    """LLM-independent **structural** pre-admission validation (default gate rejecting false lesson injection).

    Criteria (all structural and numeric; no semantic judgment or model calls):

    1. ``text`` must be non-empty.
    2. ``provenance`` must match one of the actual step signatures in ``outcome.history``
       (grounding; injected fabricated lessons are rejected because they are not tied to a
       real step).
    3. ``support`` must be at least :data:`DEFAULT_MIN_SUPPORT` (authoritative support
       recomputed by the driver, not self-reported).

    Character limits and deduplication are handled by :class:`EpisodicMemory.admit` (capacity
    policy is the memory's responsibility). If semantic validation or effect validation on a
    production distribution is needed, inject :data:`LessonVerifier` instead of this function
    (tests prove that this function is load-bearing).
    """
    if not lesson.text or not lesson.text.strip():
        return LessonVerdict(admit=False, reason="empty lesson text")
    history = getattr(outcome, "history", ())
    if lesson.provenance not in trajectory_signatures(history):
        return LessonVerdict(
            admit=False,
            reason=f"provenance {lesson.provenance!r} not grounded in trajectory",
        )
    if lesson.support < DEFAULT_MIN_SUPPORT:
        return LessonVerdict(
            admit=False, reason=f"insufficient recomputed support {lesson.support!r}"
        )
    return LessonVerdict(admit=True, reason="grounded")


@dataclass
class EpisodicMemory:
    """Bounded episodic memory. Container for lessons wired into the next context.

    Args:
        cap: Maximum number of lessons to retain. Excess lessons are evicted deterministically.
        per_lesson_chars: Character limit for one lesson's ``text`` (trimmed on admit).
        render_byte_cap: Total byte limit for the string returned by :meth:`render` (the final
            guard against next-context bloat).

    All limits prevent the "bloat and degradation of reflection output" in report.md S6
    through iteration limits. Eviction to satisfy ``cap`` uses the deterministic order
    **lowest support -> oldest episode -> oldest insertion**, and does not depend on scores
    the agent can manipulate (protecting high-support load-bearing lessons).
    """

    cap: int = 8
    per_lesson_chars: int = 512
    render_byte_cap: int = 4096
    _lessons: list[Lesson] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.cap < 1:
            raise ConfigError("EpisodicMemory cap must be >= 1")
        if self.per_lesson_chars < 1:
            raise ConfigError("EpisodicMemory per_lesson_chars must be >= 1")
        if self.render_byte_cap < 1:
            raise ConfigError("EpisodicMemory render_byte_cap must be >= 1")

    def lessons(self) -> tuple[Lesson, ...]:
        """**Read-only** view of currently retained lessons (for gather wiring)."""
        return tuple(self._lessons)

    def copy(self) -> "EpisodicMemory":
        """Return an independent copy with the same limits and lessons (for non-destructive resume seed copies).

        ``Lesson`` is frozen, so shallow-copying and sharing lessons is fine (only the
        internal list is duplicated).
        """
        clone = EpisodicMemory(
            cap=self.cap,
            per_lesson_chars=self.per_lesson_chars,
            render_byte_cap=self.render_byte_cap,
        )
        clone._lessons = list(self._lessons)
        return clone

    def __len__(self) -> int:
        return len(self._lessons)

    def _normalized(self, text: str) -> str:
        return " ".join(text.split()).lower()

    def admit(self, lesson: Lesson, verdict: LessonVerdict) -> bool:
        """Store a lesson that passed validation. Return ``True`` if it was stored.

        If ``verdict.admit`` is False, or if the normalized text duplicates an existing
        lesson, the lesson is not stored (deduplication is the memory's responsibility).
        ``text`` is trimmed to ``per_lesson_chars``. When ``cap`` is exceeded, one lesson is
        evicted in deterministic order (lowest support -> oldest episode).
        """
        if not verdict.admit:
            return False
        # Trim **before** deduplication: when per_lesson_chars is small, two lessons that
        # become identical after trimming (differing only after the trim point) could bypass
        # dedup and be stored twice with identical text. Deduplicate on the text that will
        # actually be stored.
        if len(lesson.text) > self.per_lesson_chars:
            lesson = replace(lesson, text=lesson.text[: self.per_lesson_chars])
        norm = self._normalized(lesson.text)
        if any(self._normalized(existing.text) == norm for existing in self._lessons):
            return False
        self._lessons.append(lesson)
        if len(self._lessons) > self.cap:
            self._evict_one()
        return True

    def _evict_one(self) -> None:
        """Discard one lesson when over capacity: deterministic order of lowest support -> oldest episode -> oldest insertion."""
        # min() returns the first minimum element, so list order (insertion order) is the final
        # tie-break.
        victim = min(
            range(len(self._lessons)),
            key=lambda i: (self._lessons[i].support, self._lessons[i].episode, i),
        )
        del self._lessons[victim]

    def render(self) -> str:
        """Return the lesson block wired into the next context (bounded by ``render_byte_cap``).

        Sort by descending support (prioritizing useful learning) -> ascending episode, then
        add lines one by one. Stop before adding any line whose **UTF-8 encoded byte count**
        would exceed ``render_byte_cap`` (the final bloat guard). Non-ASCII text (such as
        Japanese or emoji) is bounded by actual byte count rather than character count. Return
        an empty string when there are no lessons.
        """
        if not self._lessons:
            return ""
        ordered = sorted(self._lessons, key=lambda l: (-l.support, l.episode))
        lines: list[str] = ["## Lessons from prior episodes"]
        for lesson in ordered:
            line = f"- {lesson.text}"
            candidate = "\n".join(lines + [line])
            if len(candidate.encode("utf-8")) > self.render_byte_cap:
                break
            lines.append(line)
        if len(lines) == 1:
            # Pathological case where the header alone exceeds the cap: truncate safely at a
            # byte boundary (decode with errors='ignore' so broken multibyte sequences are not
            # left behind).
            return lines[0].encode("utf-8")[: self.render_byte_cap].decode("utf-8", "ignore")
        return "\n".join(lines)


__all__ = [
    "Lesson",
    "LessonVerdict",
    "LessonVerifier",
    "EpisodicMemory",
    "default_admit",
    "step_signature",
    "trajectory_signatures",
    "DEFAULT_MIN_SUPPORT",
]
