"""episodic memory: bounded accumulation of linguistic lessons across episodes + pre-admission validation (Issue #22).

Holds "linguistic lessons" (directives) generated by the outer Reflexion loop (report.md S4.4 / S5 Phase3)
at episode boundaries and serves as the vessel for wiring them into the next episode's context via ``render()``.
This module is a **leaf module** that depends only on ``loop_agent.state`` (StepRecord)
and has no LLM dependencies. If semantic validation is needed, inject :data:`LessonVerifier`.

Safety design (report.md S6 + RQGM / Issue #4) --- invariants guaranteed here:

- **Pre-admission validation (screening before memory intake / blocking false lesson injection)**: lessons pass through
  the **structural (LLM-independent) gate** of :func:`default_admit` before being admitted. Requires that the lesson's
  ``provenance`` matches the signature (:func:`step_signature`) of an actual trajectory step that occurred,
  ``support`` meets the threshold, and text is within the limit. Injected fabricated lessons (not linked to actual steps)
  are blocked by provenance mismatch.
- **Do not trust self-reported support**: ``Lesson.support`` is a value **recomputed and overwritten by the driver (run_reflexion)
  from an authoritative signal**, and even if the ``reflect`` hook lies, it has no effect on admission (the driver overwrites it;
  see :mod:`loop_agent.reflexion`).
- **Prevent bloat and degradation (iteration limits)**: the lesson count cap ``cap``, per-lesson character limit
  ``per_lesson_chars``, and total byte cap for ``render()`` called ``render_byte_cap`` bound both accumulation and
  rendering to the next context (mitigates report.md "4x bloat in 3 iterations").
- **Deterministic, value-aware eviction**: when overflow occurs, discard in the deterministic order
  **minimum support → oldest episode**. High-support, load-bearing lessons are not crowded out by low-support peripheral lessons
  (= effective lessons are not forgotten). Eviction order does not depend on scores that the agent can manipulate.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field, replace
from typing import Any, Callable, Sequence

from .state import StepRecord


def step_signature(record: StepRecord) -> str:
    """Returns a stable, content-based signature of a trajectory step (for provenance grounding).

    If we used only iteration, a signature like ``step-0`` would always exist and could be forged.
    Instead, we compute a short hash including observation / detail / goal_met. Only lessons citing
    steps that actually occurred will match; injected lessons without trajectory access cannot forge a matching signature.
    """
    payload = f"{record.iteration}|{record.goal_met}|{record.detail}|{record.observation!r}"
    digest = hashlib.sha256(payload.encode("utf-8", "surrogatepass")).hexdigest()
    return f"step-{record.iteration}-{digest[:12]}"


def trajectory_signatures(history: Sequence[StepRecord]) -> frozenset[str]:
    """Returns the set of signatures for all steps in the trajectory (used for provenance matching)."""
    return frozenset(step_signature(s) for s in history)


@dataclass(frozen=True)
class Lesson:
    """A single linguistic lesson (the accumulation unit of Reflexion's verbal reinforcement).

    - ``text``       : the linguistic lesson to wire into the next context.
    - ``episode``    : the source episode number (used for eviction tie-breaking and audit).
    - ``provenance`` : the signature of the source step (:func:`step_signature`). The key to grounding.
    - ``support``    : the confidence recomputed by **the driver** from an authoritative signal.
      The value set by ``reflect`` is overwritten by the driver, so this is the only value
      we can trust during admission.
    """

    text: str
    episode: int
    provenance: str
    support: float = 0.0


@dataclass(frozen=True)
class LessonVerdict:
    """Verdict of pre-admission validation. If ``admit`` is False, do not add to memory."""

    admit: bool
    reason: str = ""


# Pre-admission validation hook: (lesson, outcome) -> LessonVerdict. outcome is a read-only view
# with a ``.history`` attribute (duck typing; we avoid importing EpisodeOutcome to maintain leaf status).
# The default is :func:`default_admit` (structural). Semantic or effect-based validation can be swapped by the caller.
LessonVerifier = Callable[[Lesson, Any], LessonVerdict]


# Default threshold for the structural gate. support is a value recomputed by the driver from grounding
# (effectively 0.0 or 1.0), so requiring > 0 blocks "injected lessons not linked to actual steps".
DEFAULT_MIN_SUPPORT = 1e-9


def default_admit(lesson: Lesson, outcome: Any) -> LessonVerdict:
    """LLM-independent **structural** pre-admission validation (default gate blocking false lesson injection).

    Criteria (all structural and numerical; no semantic judgment or model calls):

    1. ``text`` must be non-empty.
    2. ``provenance`` must match one of the actual step signatures in ``outcome.history``
       (grounding; injected fabricated lessons not linked to actual steps are blocked).
    3. ``support`` must be at least :data:`DEFAULT_MIN_SUPPORT` (authority-backed recomputed support,
       not self-reported).

    Character limits and deduplication are handled by :class:`EpisodicMemory.admit` (capacity policy
    is memory's responsibility). If semantic validation or effect validation in production distribution
    is needed, inject a custom :data:`LessonVerifier` instead of this function (this function's
    load-bearing role is demonstrated by tests).
    """
    if not lesson.text or not lesson.text.strip():
        return LessonVerdict(admit=False, reason="empty lesson text")
    history = getattr(outcome, "history", ())
    if lesson.provenance not in trajectory_signatures(history):
        return LessonVerdict(
            admit=False,
            reason=f"provenance {lesson.provenance!r} not grounded in trajectory",
        )
    if lesson.support < DEFAULT_MIN_SUPPORT:
        return LessonVerdict(
            admit=False, reason=f"insufficient recomputed support {lesson.support!r}"
        )
    return LessonVerdict(admit=True, reason="grounded")


@dataclass
class EpisodicMemory:
    """Bounded episodic memory. Container for lessons to wire into the next context.

    Args:
        cap: maximum number of lessons to retain. Excess is evicted in deterministic order.
        per_lesson_chars: character limit for a single lesson's ``text`` (excess is truncated at admit time).
        render_byte_cap: total character limit for the string returned by :meth:`render` (final guard
            against bloat in the next context).

    All limits prevent "reflection output bloat and degradation" (report.md S6) through iteration limits.
    Eviction to meet ``cap`` uses the deterministic order **minimum support → oldest episode → oldest insertion**,
    independent of scores the agent can manipulate (protecting high-support, load-bearing lessons).
    """

    cap: int = 8
    per_lesson_chars: int = 512
    render_byte_cap: int = 4096
    _lessons: list[Lesson] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.cap < 1:
            raise ValueError("EpisodicMemory cap must be >= 1")
        if self.per_lesson_chars < 1:
            raise ValueError("EpisodicMemory per_lesson_chars must be >= 1")
        if self.render_byte_cap < 1:
            raise ValueError("EpisodicMemory render_byte_cap must be >= 1")

    def lessons(self) -> tuple[Lesson, ...]:
        """Returns a **read-only** view of currently held lessons (for gather wiring)."""
        return tuple(self._lessons)

    def copy(self) -> "EpisodicMemory":
        """Returns an independent copy with the same limits and lesson set (for non-destructive copying of resume seed).

        Since ``Lesson`` is frozen, we can shallow-copy and share them (only the internal list is duplicated).
        """
        clone = EpisodicMemory(
            cap=self.cap,
            per_lesson_chars=self.per_lesson_chars,
            render_byte_cap=self.render_byte_cap,
        )
        clone._lessons = list(self._lessons)
        return clone

    def __len__(self) -> int:
        return len(self._lessons)

    def _normalized(self, text: str) -> str:
        return " ".join(text.split()).lower()

    def admit(self, lesson: Lesson, verdict: LessonVerdict) -> bool:
        """Admits a lesson that passed validation. Returns ``True`` if successfully admitted.

        Rejects if ``verdict.admit`` is False or the normalized text duplicates an existing lesson
        (deduplication is memory's responsibility). ``text`` is truncated to ``per_lesson_chars``.
        When exceeding ``cap``, evicts one lesson in deterministic order (minimum support → oldest episode).
        """
        if not verdict.admit:
            return False
        # Truncate **before** dedup check: if per_lesson_chars is small, two lessons that differ only after
        # the truncation point will become identical after truncation, slip through dedup, and be duplicated.
        # We deduplicate based on the text that will actually be stored.
        if len(lesson.text) > self.per_lesson_chars:
            lesson = replace(lesson, text=lesson.text[: self.per_lesson_chars])
        norm = self._normalized(lesson.text)
        if any(self._normalized(existing.text) == norm for existing in self._lessons):
            return False
        self._lessons.append(lesson)
        if len(self._lessons) > self.cap:
            self._evict_one()
        return True

    def _evict_one(self) -> None:
        """Discards one lesson when over capacity: deterministic order of minimum support → oldest episode → oldest insertion."""
        # min() returns the first minimum element, so list order (insertion order) becomes the final tie-break.
        victim = min(
            range(len(self._lessons)),
            key=lambda i: (self._lessons[i].support, self._lessons[i].episode, i),
        )
        del self._lessons[victim]

    def render(self) -> str:
        """Returns a lesson block to wire into the next context (bounded by ``render_byte_cap``).

        Sorts by descending support (prioritizing effective lessons) → ascending episode, accumulating one line at a time.
        Lines that would cause the total **UTF-8-encoded byte count** to exceed ``render_byte_cap`` are not added and the output
        is truncated (final guard against bloat). Even non-ASCII (Japanese, emoji, etc.) is bounded by actual byte count,
        not character count. Returns an empty string if no lessons exist.
        """
        if not self._lessons:
            return ""
        ordered = sorted(self._lessons, key=lambda l: (-l.support, l.episode))
        lines: list[str] = ["## Lessons from prior episodes"]
        for lesson in ordered:
            line = f"- {lesson.text}"
            candidate = "\n".join(lines + [line])
            if len(candidate.encode("utf-8")) > self.render_byte_cap:
                break
            lines.append(line)
        if len(lines) == 1:
            # Pathological case where even the header alone exceeds the limit: safely round at byte boundary
            # (use errors='ignore' on decode to avoid leaving broken multibyte sequences).
            return lines[0].encode("utf-8")[: self.render_byte_cap].decode("utf-8", "ignore")
        return "\n".join(lines)


__all__ = [
    "Lesson",
    "LessonVerdict",
    "LessonVerifier",
    "EpisodicMemory",
    "default_admit",
    "step_signature",
    "trajectory_signatures",
    "DEFAULT_MIN_SUPPORT",
]
